### ISSUE TITLE
Output files without tests

### ISSUE THREAD

**Issue by nbdavies** [openelections/openelections-data-wi#11]
This is something I can probably help with, but just wanted to get it on the list.

**Comment by nbdavies** [comment]
Added tests back through 2008 so far.

**Comment by nbdavies** [comment]
We now have at least one test per year that had an election. A representative sampling per election would be a good goal.

**Comment by davipo** [comment]
I computed a list of output files that don't appear in wi-elections.feature tests:
	20021105__wi__general__ward.csv
	20051213__wi__special__primary__ward.csv
	20060221__wi__primary__ward.csv
	20121106__wi__special__primary__ward.csv
	20130402__wi__special__general__ward.csv
	20150217__wi__special__primary__ward.csv
	20150407__wi__special__general__ward.csv
	20150721__wi__special__general__ward.csv

**Comment by nbdavies** [comment]
There are tests for this in a PR submitted to @davipo's fork. To be combined with one more fix that he has, and then submit to core repo.

**Comment by davipo** [comment]
Thanks for writing up the tests, Nick. We now have at least one test for each results output file. All tests pass, as of commit bbe7ebe.

**Comment by nbdavies** [comment]
There are various new input files added, so now we need some tests added to get back to "one test minimum per election/output file".

**Comment by davipo** [comment]
(Actually, the new data is not yet in this repo, but should be when tests pass and merging is done.)

**Comment by davipo** [comment]
List of 20 untested results files added with PR #15 on 2018-03-28:

20110215__wi__primary__ward.csv
20110712__wi__primary-recall__ward.csv
20110712__wi__special__primary__ward.csv
20110719__wi__general-recall__ward.csv
20110719__wi__primary-recall__ward.csv
20110809__wi__general-recall__ward.csv
20110809__wi__special__general__ward.csv
20110816__wi__general-recall__ward.csv
20120221__wi__primary__ward.csv
20120508__wi__primary-recall__ward.csv
20130219__wi__primary__ward.csv
20131022__wi__special__primary__ward.csv
20131119__wi__special__general__ward.csv
20140218__wi__primary__ward.csv
20140401__wi__general__ward.csv
20150407__wi__general__ward.csv
20160216__wi__primary__ward.csv
20171219__wi__special__primary__ward.csv
20180116__wi__special__general__ward.csv
20180220__wi__primary__ward.csv

**Comment by nbdavies** [comment]
A couple more:
* 20001107__wi__general__ward.csv
* 20111108__wi__special__general__ward.csv

**Comment by davipo** [comment]
Nick added many tests for mid-2012 and later files. With recent fixes, these now pass (in davipo fork).

Remaining files without tests:

20110215__wi__primary__ward.csv
20110712__wi__primary-recall__ward.csv
20110712__wi__special__primary__ward.csv
20110719__wi__general-recall__ward.csv
20110719__wi__primary-recall__ward.csv
20110809__wi__general-recall__ward.csv
20110809__wi__special__general__ward.csv
20110816__wi__general-recall__ward.csv
20120221__wi__primary__ward.csv

**Comment by davipo** [comment]
PR #18 has been merged, it tests the remaining untested output files. I think we can close this now.
