### ISSUE TITLE
Add 2016 elections

### ISSUE THREAD

**Issue by nbdavies** [openelections/openelections-data-wi#13]
The API for the election index currently doesn't have 2016 elections:
http://openelections.net/api/v1/election/?format=json&limit=0&state__postal=WI
Then we can include those in the parser.

**Comment by dwillis** [comment]
Thanks - I'll add these, but don't process 2016 general yet; we'll wait for official results.

**Comment by dwillis** [comment]
@nbdavies I've added 2016 primaries and will add general election once official results are published.
