### ISSUE TITLE
Broken links in Metadata API

### ISSUE THREAD

**Issue by nbdavies** [openelections/openelections-data-wi#15]
Running fetch.py in the repo to download source files from the "direct_link" urls in the API includes some links that are now broken. Could be due to things getting shifted around in Wisconsin's transition from the GAB to the Elections Commission.

`
Downloading data/docview.asp?docid=6472&locid=47

Could not download file http://elections.state.wi.us/docview.asp?docid=6472&locid=47, status code 404

Downloading data/CxC_fallpri04_recount_dem_assm36.pdf  

Could not download file http://www.gab.wi.gov/sites/default/files/CxC_fallpri04_recount_dem_assm36.pdf  , status code 404

Downloading data/WxW%20Fall%20Pri04_dem%20assm36%20recount.pdf   

Could not download file http://www.gab.wi.gov/sites/default/files/WxW%20Fall%20Pri04_dem%20assm36%20recount.pdf   , status code 404

Downloading data/CxC%20results_fall04%20primary_con.pdf   

Could not download file http://www.gab.wi.gov/sites/default/files/CxC%20results_fall04%20primary_con.pdf   , status code 404

Downloading data/WxW%20fall%20primary%2004con.pdf  

Could not download file http://www.gab.wi.gov/sites/default/files/WxW%20fall%20primary%2004con.pdf  , status code 404

Downloading data/CxC%20results_fall04_primary_dem.pdf 

Could not download file http://www.gab.wi.gov/sites/default/files/CxC%20results_fall04_primary_dem.pdf , status code 404

Downloading data/WxW%20fall%20primary%2004dem.pdf     

Could not download file http://www.gab.wi.gov/sites/default/files/WxW%20fall%20primary%2004dem.pdf     , status code 404

Downloading data/CxC%20results_fall04%20primary_ind.pdf  

Could not download file http://www.gab.wi.gov/sites/default/files/CxC%20results_fall04%20primary_ind.pdf  , status code 404

Downloading data/WxW%20fall%20primary%2004ind.pdf      

Could not download file http://www.gab.wi.gov/sites/default/files/WxW%20fall%20primary%2004ind.pdf      , status code 404

Downloading data/CxC%20results_fall04_primary_lib.pdf  

Could not download file http://www.gab.wi.gov/sites/default/files/CxC%20results_fall04_primary_lib.pdf  , status code 404

Downloading data/WxW%20Fall%20primary%2004lib.pdf    

Could not download file http://www.gab.wi.gov/sites/default/files/WxW%20Fall%20primary%2004lib.pdf    , status code 404

Downloading data/CxC%20results_fall04%20primary_rep.pdf   

Could not download file http://www.gab.wi.gov/sites/default/files/CxC%20results_fall04%20primary_rep.pdf   , status code 404

Downloading data/WxW%20fall%20primary%2004rep.pdf    

Could not download file http://www.gab.wi.gov/sites/default/files/WxW%20fall%20primary%2004rep.pdf    , status code 404

Downloading data/CxC%20results_fall04_primary_wgr.pdf    

Could not download file http://www.gab.wi.gov/sites/default/files/CxC%20results_fall04_primary_wgr.pdf    , status code 404

Downloading data/WxW%20fall%20primary%2004wgr.pdf   

Could not download file http://www.gab.wi.gov/sites/default/files/WxW%20fall%20primary%2004wgr.pdf   , status code 404

Downloading data/docview.asp?docid=1444&locid=47

Could not download file http://elections.state.wi.us/docview.asp?docid=1444&locid=47, status code 404

Downloading data/docview.asp?docid=1480&locid=47

Could not download file http://elections.state.wi.us/docview.asp?docid=1480&locid=47, status code 404

no results for id:  674

no results for id:  685

no results for id:  689
`

**Comment by nbdavies** [comment]
I don't know if there's a way to fix these en masse, but the first one listed is id 439 in the JSON. A better URL for the direct_link would be:

http://elections.wi.gov/sites/default/files/2006_SpringElection_Primary_CircuitCt_WardbyWard.xls

And the portal link would be:

http://elections.wi.gov/elections-voting/results/2006/spring-primary

Looks like the paths/filenames are becoming more consistent, which is nice.

**Comment by dwillis** [comment]
Yeah, there's no super simple way of fixing these, but we'll go back and do it. Thanks!

**Comment by nbdavies** [comment]
This should now be as fixed as it can be for the moment.
