### ISSUE TITLE
Office title strips periods, which disrupts county names

### ISSUE THREAD

**Issue by nbdavies** [openelections/openelections-data-wi#16]
This is coming up with regard to things like district attorney and circuit court elections. (Which I guess aren't part of the typical openelections scope...) Currently the office name includes the county name for these county offices. But periods get stripped out of the office, so we end up with "St Croix County Circuit Court". 

Maybe that's okay, maybe not. We could try not stripping out periods and see what problems that causes. :-) I haven't spotted where this is happening in parser.py though.

**Comment by dwillis** [comment]
I think that's probably ok, but if we can isolate where it's happening in the parser (if that's the case) and can fix it, that would be great.

**Comment by nbdavies** [comment]
This is actually how it was in the source data so I think we are okay.
