### ISSUE TITLE
Republican State Senate results not in CSV for 2008-09-09

### ISSUE THREAD

**Issue by nbdavies** [openelections/openelections-data-wi#17]
CSV file: 20080909__wi__primary_ward.csv

This should, for example, include Chad Fradette as a state senate candidate in Green Bay. It's present in the source data (Republican_2008_FallElection_StateSenator_WardbyWard.xls). Not sure where it's getting lost along the way.

**Comment by nbdavies** [comment]
@davipo has a fix for this in his branch

**Comment by davipo** [comment]
Parser had stopped reading the input spreadsheet after three rows with column A blank. Corrected that to process the missing data. Test passes, can we close this?
