### ISSUE TITLE
2008-09-09 State Assembly Results are cumulative/redundant

### ISSUE THREAD

**Issue by nbdavies** [openelections/openelections-data-wi#18]
For the 2008-09-09 election, the direct links for State Assembly results are:

- "http://www.gab.wi.gov/sites/default/files/WisconsinGreen_2008_FallElection_StateAssembly_WardbyWard.xls",
-  "http://www.gab.wi.gov/sites/default/files/Republican_2008_FallElection_StateAssembly_WardbyWard.xls",
-  "http://www.gab.wi.gov/sites/default/files/Libertarian_2008_FallElection_StateAssembly_WardbyWard.xls",
-  "http://www.gab.wi.gov/sites/default/files/Independent_2008_FallElection_StateAssembly_WardbyWard.xls",
-  "http://www.gab.wi.gov/sites/default/files/Democratic_2008_FallElection_StateAssembly_WardbyWard.xls"

Contrary to what the file names imply, each of these files include the state assembly results for all parties. This leads to double-reporting in our CSV output. 

Either we should only include one these files for processing, or we would need to build this one exception into the parser, to be the only time where we don't process all of the direct links for an election.

**Comment by davipo** [comment]
We modified parser.process() to skip missing input files, and renamed all but one of them in local_data_cache as a temporary solution. Probably need Wisconsin Election Commission to rename the input file correctly. Would like to remove redundant files from direct links in metadata.

**Comment by nbdavies** [comment]
This should now be fixed in the source data: only one copy of the file is referenced in the API.
