### ISSUE TITLE
2012-08-14 file for D.A. race contains Assembly results instead

### ISSUE THREAD

**Issue by nbdavies** [openelections/openelections-data-wi#19]
In election 411, these linked files contain the same results:

"http://www.gab.wi.gov/sites/default/files/Ward%20x%20Ward%20Results_8.14.12%20primary_Assembly.xls",
        "http://www.gab.wi.gov/sites/default/files/Ward%20x%20Ward%20Results_8.14.12%20primary_D.A..xls",

The second file should probably contain results for district attorney (based on the file name anyway), but it contains the same Assembly results as the first file.

**Comment by davipo** [comment]
For a temporary solution, we renamed the copy of the D.A. file in our local_data_cache, so it will be skipped and not produce duplicated results. Consider removing this file from metadata, until it is corrected.

**Comment by nbdavies** [comment]
I've changed the source file list to refer to the PDF version of the DA results. The PDF version does contain the right data, even if we haven't worked out how to parse PDFs reliably.

**Comment by nbdavies** [comment]
With some encouragement, Wisconsin Elections Commission has put an Excel file on their site:
http://elections.wi.gov/sites/default/files/2012%20Partisan%20Primary%20District%20Attorney.xlsx
It's not laid out in the same way as their other Excel files (WEC's spokesman said they no longer have what they would need to produce this file in that layout).

Once we have the parser updated to handle this file, we can close this out.

**Comment by davipo** [comment]
Parser was updated July 11 to handle this file. Added a couple of tests for this election, they pass.
