### ISSUE TITLE
total votes is 0 in 2012-08-14 D.A. primary election results

### ISSUE THREAD

**Issue by davipo** [openelections/openelections-data-wi#29]
The input file for this election has an unusual format. It is not simple to compute total votes for each reporting unit. This calculation has not been implemented. The total votes field in the results for county D.A.s is currently 0.

Results file is 20140812__wi__primary__ward.csv

**Comment by nbdavies** [comment]
There's a fix for this in PR https://github.com/davipo/openelections-data-wi/pull/13

**Comment by davipo** [comment]
Merged PR #13, fixed issue #30, added a test to check summing of total votes in this file. Tests pass.
