### ISSUE TITLE
La Crosse County Misspelled

### ISSUE THREAD

**Issue by nbdavies** [openelections/openelections-data-wi#35]
This came to light when I tried to run the `load` utility in the openelections-core repo. This tried to match county name from the CSVs in this repo to OCD IDs. 

It failed, because there is no "Lacrosse" county in Wisconsin, but "Lacrosse" appears in about 1/3 of our CSV data, and "La Crosse" (correct) in the other 2/3. 

There are also office names that include the incorrect county name, including circuit court and district attorney.

**Comment by davipo** [comment]
Do we have sufficient tests for this issue? If so, can it be closed?

**Comment by nbdavies** [comment]
Yup, the fix included updates to the test file that would catch this problem.
