### ISSUE TITLE
Circuit court branch with/without comma

### ISSUE THREAD

**Issue by nbdavies** [openelections/openelections-data-wi#37]
According to @davipo:

> Some Circuit Court office names use a comma before Branch, and some do not. There are examples without commas in our tests for 2016 and 2017.

An example without the comma, in `2016/20160216__wi__primary__ward.csv`:
```
Portage,Town Of Alban Ward 1,Portage County Circuit  Court Branch 2,,107,NP,Trish Baker,40
```
An example with the comma, in `2014/20140401__wi__general__ward.csv`:
```
Barron,Town Of Almena Wards 1-2,"Barron County Circuit Court, Branch 2",,69,NP,J. Michael Bitney,69
```
There are about 31,000 lines of output without the comma vs 166,000 with comma, so I think "with comma" wins?

**Comment by davipo** [comment]
This inconsistency was noted in Issue #22.
Revised clean_office() to add a comma where missing between "Court" and "Branch".
This updated 4 results files, from 2016 to 2018.
3 tests updated, added a test for 2016-02-16.
Please review and close issue if appropriate.
