### ISSUE TITLE
2012-05-08 includes office "Recall State Senate-21 - Democratic" (should be "State Senate")

### ISSUE THREAD

**Issue by nbdavies** [openelections/openelections-data-wi#41]
For context, election 1830 (date 2012-05-08) is a recall primary election for governor, lieutenant governor, and state senate.

The office name for the state senate results in our output is currently "Recall State Senate-21 - Democratic" and should just be "State Senate".

Here's an example output row:
```
Racine,"Village Of Mount Pleasant Wards 10,11,12,15",Recall State Senate-21 - Democratic,,1256,DEM,Tamra Varebrook,390
```
"21" belongs in the District column instead, which is currently empty. We're already picking up "DEM" for the party.

**Comment by davipo** [comment]
Nick, I tested my fix for this and other improvements with your test file of 2018-05-08 (see my commits today). One filename used the wrong date. Some direct links were missing from the metadata for id 404 (2013-04-02). All tests passed after fixing those problems. If those tests cover this issue, I think it can be closed. (Hard to tell without a district field, I created Issue #42 for that.)
