### ISSUE TITLE
Adding ward-level data via Open Data Portal/ArcGIS

### ISSUE THREAD

**Issue by pjrule** [openelections/openelections-data-wi#44]
Wisconsin has [released election data](https://data-ltsb.opendata.arcgis.com/) in CSV format at a finer resolution than what OpenElections currently offers. Currently, wards are frequently lumped together in the OpenElections data (see ward names like "Town Of Merton Ward 1-3,7-9"), whereas the Wisconsin data on the ArcGIS website is broken out by individual wards. I'd be more than happy to try to integrate this data with what's currently available from OpenElections if anyone's interested. The only caveat is that individual candidate names are not included with the ArcGIS data, though that may be fixable.

**Comment by nbdavies** [comment]
Hi @pjrule,
Check out #21 as well; @epaulson was able to do some cool things with the LTSB data you linked to.

There are some drawbacks to the LTSB data to be aware of:
* It has ward-level vote counts, but those are statistically disaggregated from the reporting units that the WEC publishes. Meaning that LTSB doesn't really have finer detail, they're just estimating.
* To apply 2017 ward boundaries to 2002 election results for example, LTSB has to further disaggregate the results based on the 2002 ward shapes, and then aggregate them according to the 2017 ward shapes. This means that some of their results don't match the WEC-certified results.
* They also only include the biannual elections, while WEC publishes results for all federal and state elections.

So using LTSB data for the Openelections project would involve trade-offs. Maybe @dwillis would have more background on whether contributors to other states' repos have had to decide between this kind of disaggregated data vs. certified results.

**Comment by pjrule** [comment]
Interesting! I didn't realize that the LTSB data is disaggregated. With that in mind, it seems like it's probably better to stick with the WEC data in this case.
