### ISSUE TITLE
Party is missing from many tests

### ISSUE THREAD

**Issue by davipo** [openelections/openelections-data-wi#48]
Our parser captures party data from many input files, but many of our tests don't check this field. We test it mainly for primary elections, but also for several general elections. Because party data is in our results files, it should be tested.

(The party field is needed to distinguish "Scattering" records in primary elections.)

To add party data to the tests, it should be looked up manually in the input files, to guarantee an independent test. Currently about 74 tests need party data. (109 tests specify party, about 97 are for nonpartisan offices.)

Please edit the wi-elections.feature.csv file to add party data. (The older format wi-elections.feature file may be removed, since it is not used by the new faster testing program.)

**Comment by nbdavies** [comment]
This will be addressed in https://github.com/davipo/openelections-data-wi/pull/21

**Comment by davipo** [comment]
Thanks Nick, for looking up and adding party to many tests.
I've revised run_spot_tests.py to always test party, even when empty. (Removed kludge to skip party test when party is empty in test data.) All tests now pass.
