### ISSUE TITLE
St Croix and Saint Croix should be the same county

### ISSUE THREAD

**Issue by nbdavies** [openelections/openelections-data-wi#53]
In the county column, it's called `St. Croix`.

The circuit court office name is inconsistent:
* `Saint Croix County Circuit Court, Branch x` (6 elections)
* `St Croix County Circuit Court, Branch x` (4 elections)

For the county's DA, the office name is also a mix: 
* `St. Croix County District Attorney` (4 elections)
* `Saint Croix County District Attorney` (3 elections)

For consumers of this data that might slice it by office name,  it'd be nice to coalesce these spellings so that they don't have to.

`St. Croix` would be the best name to standardize to, so that it matches the county column. There are 13 files total that have the other two variants (`Saint Croix`/`St Croix`) that should show up as modified when a fix is in place.

**Comment by davipo** [comment]
We fixed this with commit b000d3f

https://github.com/davipo/openelections-data-wi/commit/b000d3fe23a8c651b30faf7672a02de4f58a9c55
